## https://www.appveyor.com/docs/appveyor-yml/
image: Ubuntu2004
version: 1.0.{build}

configuration:
- Debug

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: true
  
nuget:
  disable_publish_on_pr: true

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: 0rxw6OrmXRqB3UuBZFbC/w==
  SONAR_TOKEN:
    secure: iMwieUAbbS4oTgEVtdGWUujzaBkeNjhFzsPMj8Y3c8vkjWyCN2miKlyfWA25jtBr
  CONFIGURATION: Debug

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: $env:DOCKER_PASS | docker login --username $env:DOCKER_USER --password-stdin
- docker version

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

build_script:
- ps: >-
    $buildNumber = $env:APPVEYOR_BUILD_NUMBER;
    $branch = $env:APPVEYOR_REPO_BRANCH;
    .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber -pushImage;
    $fileVersion = $env:APPVEYOR_BUILD_VERSION;
    dotnet build src/Cortside.Authorization.Client --configuration $env:CONFIGURATION /property:"Version=$fileVersion";

after_build:
- ps: >-
    $branch = $ENV:APPVEYOR_REPO_BRANCH;
    $fileVersion = $env:APPVEYOR_BUILD_VERSION;
    if($branch -ne 'master') {
        $fileVersion = "${fileVersion}-${branch}"; 
    }
    
    $fileVersion = $fileVersion.replace("release/", "release-");
    $fileVersion = $fileVersion.replace("feature/", "");
    $fileVersion = $fileVersion.replace("bugfix/", "");
    dotnet pack src/Cortside.Authorization.Client --include-symbols -p:SymbolPackageFormat=snupkg --configuration $env:CONFIGURATION -o ((get-location).Path + '\artifacts') /property:Version=$fileVersion 
    
artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
   
deploy:
- provider: NuGet
  api_key:
    secure: D7B7/pzGIeteV3H4DrdBtyKCxLrgcBAL6XWtWrm/kJrshDwUZ5acauR9QWll7TWi
